name: recover_me
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  conditional_builder_null_safety: ^0.0.6
  fl_chart: ^0.62.0
  image_picker: ^0.8.7+2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.0.1
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  firebase_messaging: ^14.2.2
  cloud_firestore: ^4.4.0
  firebase_core_platform_interface: 4.5.3
  firebase_storage: ^11.0.11
  palette_generator: ^0.3.3+2
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.3
  flutter_image_compress: ^1.1.3
  intl: any
  google_sign_in: ^6.1.0
  pull_to_refresh: ^2.0.0
  readmore: ^2.1.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
