name: recover_me
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  conditional_builder_null_safety: ^0.0.6
  fl_chart: ^0.62.0
  image_picker: ^0.8.7+5
  cupertino_icons: ^1.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.1.0
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  #firebase_messaging: ^14.6.1
  cloud_firestore: ^4.7.1
  firebase_core_platform_interface: ^4.8.0
  firebase_storage: ^11.2.1
  palette_generator: ^0.3.3+2
  fluttertoast: ^8.2.2
  cached_network_image: ^3.2.3
  flutter_image_compress: ^2.0.3
  intl: any
  google_sign_in: ^6.1.0
  pull_to_refresh: ^2.0.0
  readmore: ^2.2.0
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.1
  pinput: ^2.2.31
  flutter_svg: ^2.0.5
  flutter_spinkit: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
